name: word_wolf_tomonokai_public
description: Word Wolf web app that will be used during Tomonokai programs.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
#  linter
  clay_containers: ^0.3.2
# https://pub.dev/packages/clay_containers
# webでも使用可能なneuromorphic design作成パッケージ
  hooks_riverpod: ^2.2.0
# https://pub.dev/packages/hooks_riverpod
# 状態管理パッケージ
  flutter_riverpod: ^2.2.0
# https://pub.dev/packages/flutter_riverpod
# 状態管理パッケージ
  google_fonts: ^4.0.3
# https://pub.dev/packages/google_fonts
# Google Fontsを使用可能にするパッケージ
  responsive_sizer: ^3.1.1
# https://pub.dev/packages/google_fonts
# クライアント側の画面サイズに応じてデザインサイズを可変にする事ができるパッケージ
  ionicons: ^0.2.2
# https://pub.dev/packages/ionicons
# ioniconが使用可能になるパッケージ
  quickalert: ^1.0.1
# https://pub.dev/packages/quickalert
# Dialogを簡単に画面上に表示できるパッケージ
  modal_bottom_sheet: ^2.1.2
# https://pub.dev/packages/modal_bottom_sheet
# スマホアプリのように下からmodal dialogを出す事ができるパッケージ
  firebase_core: ^2.6.0
# https://pub.dev/packages/firebase_core
# firebase_optionのファイルに必要
flutter:
  uses-material-design: true

  assets :
    - assets/
